# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZegoLiveAudioRoomDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZegoLiveAudioRoomDemo
  pod 'ZIM'
  pod 'ZegoExpressEngine/Audio'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

end
